[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "back.py"
name = "Back"
icon = "ğŸ”™"

[[pages]]
path = "settings.py"
name = "Settings"
icon = "âš™ï¸"

[[pages]]
path = "favorites.py"
name = "Favorites"
icon = "â­"

[[pages]]
path = "page1.py"
name = "User settings"
icon = "ğŸ•µï¸"

[[pages]]
path = "page2.py"
name = "Billing settings"
icon = "ğŸ•µï¸"

[[pages]]
path = "page3.py"
name = "Cool page 1"
icon = "ğŸ˜"

[[pages]]
path = "page4.py"
name = "Cool page 2"
icon = "ğŸ˜"